GET  http://localhost:3000/products

########

POST http://localhost:3000/products
Content-Type: application/json


{
"name":"hat",
"price":"350"
}

########
DELETE  http://localhost:3000/products/2


########
PUT http://localhost:3000/products/2
Content-Type: application/json

{
    "name":"shirt",
    "price":"900"
}
